### ISSUE TITLE
Error - Unity Version Control

### ISSUE THREAD

**Issue by thecrazytech1** [Casual-Cynic/Simple-NDI-Multiview#1]
![image](https://github.com/Casual-Cynic/Simple-NDI-Multiview/assets/69059820/625b9636-a7ea-4a4a-ac69-36007600fbe2)

How do I fix that :P

**Comment by Casual-Cynic** [comment]
Hello! Were you trying to run the release build Dev 0.1.0 or were you trying to run from the source? Any additional information would be greatly appreciated so I can get more documentation sorted out and fix any sort of issues not present on my machine.

**Comment by thecrazytech1** [comment]
I was trying to run it from source (forked and then cloned the repo locally)

**Comment by Casual-Cynic** [comment]
Noted. First thing tomorrow I'll get sifting through that to try and figure out why that would be. First thing I can think of though would be to check to make sure you have the NDI package mentioned on the readme installed locally and correctly, as well as the correct version of Unity selected. Again, I'll get back to you with details tomorrow but that's just a starting place.

**Comment by Casual-Cynic** [comment]
Fixed this by removing Plastic from the project. Wasn't using it anyway
